export * from './departamento.entity';
export * from './cargo.entity';
export * from './rol.entity';
export * from './usuario.entity';
export * from './empleado.entity';
export * from './asistencia.entity';
export * from './tipoLicencia.entity';
export * from './solicitudLicencia.entity';
export * from './saldoLicencia.entity';
